language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codeclimate-test-reporter
  - pip install pytest pytest-cov
  - pip install coverage

service:
  -postgres
before_script:
  - psql -c "CREATE DATABASE admin;" -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'admin';" -U postgres
  - psql -c "CREATE TABLE IF NOT EXISTS users (user_id SERIAL,email VARCHAR(30), 
    password VARCHAR(20), handphone INTEGER, username VARCHAR(16), 
    admin BOOLEAN DEFAULT False, PRIMARY KEY (username));"
#cache
cache: pip
# command to run tests
script:
  - pytest --cov=./ 
#after successful run
after_success:
  - coveralls
  - codeclimate-test-reporter