language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codeclimate-test-reporter
  - pip install pytest pytest-cov
  - pip install coverage
#cache
cache: pip
# command to run tests
script:
  - pytest --cov=./ 
#after successful run
after_success:
  - coveralls
  - codeclimate-test-reporter